### ISSUE TITLE
how to plot motifs with negative enrichment

### ISSUE THREAD

**Issue by cxtaslim** [fmicompbio/monaLisa#70]
Hi,

 I cannot figure out how to plot the motifs with negative enrichment.
For example in your vignette, the following code plots the motifs that are enriched in one of the two groups with an adjusted p values of less than 10^-4.

```
sel2 <- apply(assay(se2, "negLog10Padj"), 1, 
             function(x) max(abs(x), 0, na.rm = TRUE)) > 4.0
sum(sel2)

plotMotifHeatmaps(x = se2[sel2,], which.plots = c("log2enr", "negLog10Padj"), 
                  width = 1.8, cluster = TRUE, maxEnr = 2, maxSig = 10,
                  show_seqlogo = TRUE)
```
![image](https://github.com/fmicompbio/monaLisa/assets/165412218/3c3b2000-d589-4cf6-9c0c-04424a19dbba)

How do I plot for only CTCF and CTCFL that shows negative enrichment in the second set.

Thank you!

**Comment by csoneson** [comment]
To plot only the rows with a negative enrichment in the second bin, you would have to add that as a selection criterion when subsetting your `SummarizedExperiment` (the `se2[sel2, ]` part). The enrichments are stored in the `log2enr` assay (see [the vignette](https://fmicompbio.github.io/monaLisa/articles/monaLisa.html#quick) for an overview of the different assays), so you could do something like 

```
## Rows with adjusted p-value < 1e-4
sel2 <- apply(assay(se2, "negLog10Padj"), 1, 
              function(x) max(abs(x), 0, na.rm = TRUE)) > 4.0
## Rows with negative log2 enrichment in second column
selneg <- assay(se2, "log2enr")[, 2] < 0
## Number of rows satisfying both conditions
sum(sel2 & selneg)
## [1] 2

plotMotifHeatmaps(x = se2[sel2 & selneg,], which.plots = c("log2enr", "negLog10Padj"), 
                  width = 1.8, cluster = TRUE, maxEnr = 2, maxSig = 10,
                  show_seqlogo = TRUE)
```

**Comment by cxtaslim** [comment]
Thank you so much for your help. Appreciate it!

Do you have any recommendation on how to further narrow down the motifs? 
In my dataset, I have more than 200 motifs even with FDR < 10^-40

Also, is there a way to print the names of the sets below the heatmap?

Thank you again!

**Comment by mbstadler** [comment]
Hi @cxtaslim 

Thanks for your interest in `monaLisa`. Unfortunately, it is currently not possible to print the names of the sets in `plotMotifHeatmaps`. It is our plan to add this in a future version of the package.

Regarding your question of how to narrow down motifs, there is no simple recipe to do this.
Depending on the context, I have been using different approaches for motif prioritisation, including:

- Increase the threshold for `"negLog10Padj"`
- If that is possible for your context, intersect the results of multiple independent motif analyses that can be expected to be driven by the same transcription factor(s).
- Use orthogonal data to restrict the set of motifs: If you have transcriptomics data, you could for example exclude motifs from transcription factors that are not expressed in your system, or if you have time-course data and are perturbing your system at a defined time-point, you could exclude motifs from factors that do not show expected time-dependent expression patterns.
- Grouping similar motifs: Many transcription factors bind to similar motifs, and as the binned motif analysis is run independently for each motif, you may get a signal for several similar motifs, even if only one of them is relevant in your experimental system. In such cases, it may help to cluster similar motifs (for example as described in the vignette using stability selection ([link to vignette](https://fmicompbio.github.io/monaLisa/articles/selecting_motifs_with_randLassoStabSel.html#identify-important-tfs)), and try to identify the relevant member(s) of each cluster using orthogonal methods.
- Identify the relevant motifs using [`randLassoStabSel`](https://fmicompbio.github.io/monaLisa/reference/randLassoStabSel.html) (instead of using [`calcBinnedMotifEnrR`](https://github.com/fmicompbio/monaLisa)). In this approach, all motifs have to "compete" with each other in order to explain the observed measurements for genomic regions. The regression approach will try to select the most pertinent motif(s) and typically will not include all members of a group of similar motifs in the selected results, however in cases where the motifs are highly similar, the inherent difficulty to discriminate them remains and the results are not guaranteed to be correct.

I hope this helps.

**Comment by cxtaslim** [comment]
@mbstadler,

That's very helpful. Thank you very much for your insights!

**Comment by mbstadler** [comment]
You are welcome. 

I will close the issue for now. Feel free to reopen it or a new one if required.
