### ISSUE TITLE
not reproducible results - set.seed is not considered by calcBinnedMotifEnrR

### ISSUE THREAD

**Issue by NathanHarmston** [fmicompbio/monaLisa#77]
Hi, 

So I am using calcBinnedMotifEnrR to calculate enrichment for a set of regions compared to the genome. However, the results are not reproducible between different runs of the same piece of code. 

```
set.seed(42)
se.dc1 <- calcBinnedMotifEnrR(seqs = prom.seqs.dc1, 
                              background="genome", 
                              genome.regions = bg, 
                              pwmL=pwms, 
                              genome=BSgenome.Hsapiens.UCSC.hg38, genome.oversample=20, min.score="80%")
```

As an example one time - I get argfx, lin54, zic2 as significant, the next time only argfx appears as significant. 

It seems that sampling from genome.regions does not consider the call to set.seed - is there anyway to fix this issue?

**Comment by csoneson** [comment]
Hi @NathanHarmston - did you try to set the `RNGseed` parameter of the `SerialParam`/`MulticoreParam` instance set for the `BPPARAM` argument? See the [**Details**](https://fmicompbio.github.io/monaLisa/reference/calcBinnedMotifEnrR.html#details-1) section of `?calcBinnedMotifEnrR`:

> **genome**
: sequences randomly sampled from the genome (or the intervals defined in genome.regions if given)
[...]
In order to make the sampling deterministic, a seed number needs to be provided to the RNGseed parameter in [SerialParam](https://rdrr.io/pkg/BiocParallel/man/SerialParam-class.html) or [MulticoreParam](https://rdrr.io/pkg/BiocParallel/man/MulticoreParam-class.html) when creating the BiocParallelParam instance in BPPARAM.

**Comment by NathanHarmston** [comment]
figured I was being a muppet! Thanks
